### ISSUE TITLE
could not get message class for topic type "vl53l1x/MeasurementData" on topic "/rangefinder/data"

### ISSUE THREAD

**Issue by NorCALUAVs** [okalachev/vl53l1x_ros#13]
raspi 4b, ros-noetic, 
im using a pre-made image from coex.tech/clover. Ive connected up my rangefinder, and get the could not get message class for topic type "vl53l1x/Measurement/Data" on topic "/rangefinder/data". Disconnected rangefinder, connected to arduino to test - works fine..
tried pulling repo down and recompiling, to no avail. ive searched everywhere looking for a cause for the error, but im at a loss right now. any help is appreciated.

**Comment by okalachev** [comment]
Hi! Do you use the prebuilt image with quadcopter's software (https://clover.coex.tech/en/image.html) or you installed the Debian package on your system from http://packages.coex.tech/packages/buster/ros-noetic-vl53l1x/?

What exactly do you do to get this error?

**Comment by NorCALUAVs** [comment]
the prebuilt image from coex.tech was what i started with, and after i got that error, i pulled the repo and rebuilt. and got the same error..

**Comment by okalachev** [comment]
The prebuilt image doesn't require you to start the driver, it already has it started along with other quadcopter software. If you don't need it you should actually stop it:

```bash
sudo systemctl stop clover
```

Then you may start only the driver separately:

```bash
rosrun vl53l1x vl53l1x_node
```

But what to you exactly do you do to see this error, where do you see it? What was you command and where have you invoked it?

Also `rangefinder/data` is a topic with the additional data, the main measurements are in `rangefinder/range`.
