### ISSUE TITLE
extension to N sensors

### ISSUE THREAD

**Issue by tiralonghipol** [okalachev/vl53l1x_ros#5]
hi !
first of all thank you for this great package
is there any chance it can be extended to N sensors using the 'i2c address reset' (essentially using the xshut pin) approach?  [https://forum.pololu.com/t/using-multiple-vl53l1x-with-raspberry-pi/16651/17]
I had it work with the vl53l0x but I would like to try it with this sensor (longer range) and the API are quite different

Thank you in advance!

**Comment by okalachev** [comment]
Hello.

I believe the much more ROS way is to have one node running per each device, but that's seems impossible without preliminary changing the addresses of each rangefinder.

So what if to have something (a script, a node, ...) that will sequentially change the addresses of each device, and only after that to have necessary count of these nodes running, each with adjusted `i2c_address` parameter in appropriate way?

**Comment by tiralonghipol** [comment]
the idea is to have a 'ring' of sensors to have a 360 degree coverage on the horizontal plane

What is required to get something similar to this: https://github.com/mjbogusz/vl53l0x-linux/blob/master/examples/continuousMultipleSensors.cpp ?

**Comment by okalachev** [comment]
I get your idea. I guess there is two options:

* Extend my node to add support running for multiple rangefinders. This is a pretty huge change, and also seems not too much ROS way to me (where one node per one device usually used).
* Write a program or script, that changes addresses of each rangefinder connected, and only after that run N instances of this node, each for each rangefinder. This solution is more universal and can be used not only with this package.

**Comment by tiralonghipol** [comment]
all right 
could you be more specific on 'huge change' on method 1 ?
for example, where can I find documentation on how to write my own i2c/gpio functions? 
like the one declared in the API https://github.com/okalachev/vl53l1x_ros/blob/master/vl53l1x/lib/platform/vl53l1_platform.h
regarding the VL53L1_GPIO*

**Comment by okalachev** [comment]
Here is my implementation of I2C functions, that are needed to the library, based on Linux API: 
* https://github.com/okalachev/vl53l1x_ros/blob/master/vl53l1x/lib/platform/vl53l1_platform.c
* https://github.com/okalachev/vl53l1x_ros/blob/master/vl53l1x/src/i2c.cpp.

The change is to update the API of the node a little, to make it possible to configure multiple I2C addresses and multiple set of parameters for each I2C address. Adding preliminary procedure for updating the addresses of the rangefinders.  Plus publishing multiple result topics, each in its own namespace.

But as I said, personally I like the method 2 more.
